package com.csye6225.fall2019.courseservice.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "board")
public class Board {
    private String id;
    private String boardId;
    private String courseId;

    public Board(){}

    public Board(String boardId, String courseId) {
        this.boardId = boardId;
        this.courseId = courseId;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBIndexHashKey(attributeName = "boardId", globalSecondaryIndexName = "boardId-index")
    public String getBoardId() {
        return boardId;
    }
    public void setBoardId(String boardId) {
        this.boardId = boardId;
    }

    @DynamoDBAttribute(attributeName = "courseId")
    public String getCourseId() {
        return courseId;
    }
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }
}
